### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by lostopkk** [clumsyc/decoration-mod#2]
[message.txt](https://github.com/clumsyc/decoration-mod/files/9669856/message.txt)

**Comment by clumsyc** [comment]
Hm... weird. That should not be happening.
Can you test this one? Just unzip and replace your old one.
[FEFabric-UNZIP THIS.zip](https://github.com/clumsyc/decoration-mod/files/9680870/FEFabric-UNZIP.THIS.zip)

**Comment by Crendgrim** [comment]
Greetings! This bug was also reported to me as it occurred in combination with my mod, DynamicCrosshair: Crendgrim/DynamicCrosshairCompat#5
For context, I create a fake item placement context to see if the held item can be placed as a block in the looked at place. Investigating the crash led me to a way to replicate this crash with only your mod (and fabric-api) installed:

Hold an item of type "toilet paper roll" in your hand. Try to place it against the floor or ceiling.

This crash happens because the safeguard here is not complete: https://github.com/clumsyc/decoration-mod/blob/f9b69ba49f5318f267c8d8ead6535e0b2a257133/src/main/java/me/clumsycat/furnitureexpanded/blocks/PaperHolder.java#L60

You make sure to only rotate when you are in a horizontal direction; but still erroneously return with Up/Down as the "facing" value if the item is being placed against a floor / ceiling. As far as I can tell, the vanilla way here would be to return "null" if the faced block face is Up or Down.

**Comment by clumsyc** [comment]
I didn't even noticed that, thanks for pointing it out. Turns out that the problem was pretty much what you said. 
I ended up using `context.getPlayerLookDirection` when I was porting to fabric, which returns all possible direction values. Using `context.getPlayerFacing`, which just return the horizontal values, fixed the problem.
https://github.com/clumsyc/decoration-mod/blob/f9b69ba49f5318f267c8d8ead6535e0b2a257133/src/main/java/me/clumsycat/furnitureexpanded/blocks/PaperHolder.java#L59
https://github.com/clumsyc/decoration-mod/blob/f9b69ba49f5318f267c8d8ead6535e0b2a257133/src/main/java/me/clumsycat/furnitureexpanded/blocks/PaperHolder.java#L72

I will be uploading the fixed version soon.
